# Generated by Django 5.1.2 on 2025-05-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='is_active',
            new_name='published',
        ),
    ]
