# Generated by Django 5.1.2 on 2025-06-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, unique=True),
        ),
    ]
