# Generated by Django 5.1.2 on 2025-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochure',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='brochure_thumbnails/'),
        ),
    ]
