# Generated by Django 5.1.2 on 2025-02-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_brochure_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochure',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='brochure-thumbnails/'),
        ),
    ]
